apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-mount
              mountPath: /prometheus
      volumes:
        - name: prometheus-mount
          persistentVolumeClaim:
            claimName: prometheus-volume