apiVersion: v1
kind: Service

metadata:
  name: pauloerweber-guia-infnet-service
spec:
  type: NodePort
  selector:
    app: pauloerweber-guia-infnet
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001