apiVersion: apps/v1
kind: Deployment
metadata:
  name: pauloerweber-guia-infnet-deploy

spec:
  replicas: 4
  selector:
    matchLabels:
      app: pauloerweber-guia-infnet
  template:
    metadata:
      labels:
        app: pauloerweber-guia-infnet
    spec:
      containers:
      - name: pauloerweber-guia-infnet
        image: pauloerweber/pauloweberinfnet-infnet-guia:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
