apiVersion: apps/v1
kind: Service

metadata:
  name: pauloerweber-guia-infnet-service
spec:
  type: NodePort
  selector:
    app: pauloerweber-guia-infnet
  ports:
    - port: 3000
    targetPort: 3000
    nodePort: 30001