apiVersion: v1
kind: Pod

metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: app-db
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
      volumeMounts:
        - name: mysql-mount
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-mount
      persistentVolumeClaim:
        claimName: mysql-volume